image: python:3.7-alpine3.9 

stages:
  - test
  - production

production:
  stage: production
  script:
    - ls -la
    - 'which ssh-agent || ( apk add --no-cache  openssh-client rsync )'
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - echo $SSH_PRIVATE_KEY > ~/.ssh/id_rsa
    - chmod 700 ~/.ssh/id_rsa
    - ls -la ~/.ssh/id_rsa
    - cat ~/.ssh/id_rsa
    - ssh -v 192.99.151.132
    - rsync -avuz -e 'ssh -i ~/.ssh/id_rsa' $CI_PROJECT_DIR/ root@192.99.151.132:~/savemyprint-gitlab
  only:
    - master   
