image: python:3.7-alpine3.9 

stages:
  - test
  - production

production:
  stage: production
  script:
    - ls -la
    - 'which ssh-agent || ( apk add --no-cache  openssh-client rsync )'
    - eval $(ssh-agent -s)
    - mkdir -p ${HOME}/.ssh
    - echo $SSH_PRIVATE_KEY > ${HOME}/.ssh/id_rsa
    - echo $SSH_HOST_KEY > ${HOME}/.ssh/known_hosts
    - chmod 700 ${HOME}/.ssh/id_rsa
    - ls -la ${HOME}/.ssh/id_rsa
    - ssh -v 192.99.151.132 -i ${HOME}/.ssh/id_rsa
    - rsync -avuz -e 'ssh -i ${HOME}/.ssh/id_rsa' $CI_PROJECT_DIR/ root@192.99.151.132:~/savemyprint-gitlab
  only:
    - master   
