image: python:3.7-alpine3.9 

stages:
  - test
  - production

production:
  stage: production
  script:
    - 'which ssh-agent || ( apk add --no-cache  openssh-client rsync )'
    - eval $(ssh-agent -s)
    - mkdir -p $HOME/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > $HOME/.ssh/id_rsa
    - echo $SSH_HOST_KEY > $HOME/.ssh/known_hosts
    # - ssh-keyscan -H 'your.server.hostname' >> ~/.ssh/known_hosts
    - chmod 700 $HOME/.ssh/id_rsa
    - ssh -i $HOME/.ssh/id_rsa root@192.99.151.132 'echo $CI_COMMIT_SHA'
    # - ssh -vT 192.99.151.132 -i $HOME/.ssh/id_rsa
    - rsync -avuz -e 'ssh -i $HOME/.ssh/id_rsa' $CI_PROJECT_DIR/ root@192.99.151.132:$HOME/savemyprint-gitlab/$CI_COMMIT_SHA
    - ssh -i $HOME/.ssh/id_rsa root@192.99.151.132 '( cd $HOME/savemyprint-gitlab;  echo "$CI_COMMIT_SHA/"  )'
    # - ssh -i $HOME/.ssh/id_rsa root@192.99.151.132 '( cd $HOME/savemyprint-gitlab; rsync -rlch --progress --stats --delete --exclude 'app/static/uploaded' $CI_COMMIT_SHA/ webapp/ )'
  only:
    - master   
